apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6xef
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ccba-tenant/rhtap-demo-app/hacbs-test-project-6xef@sha256:9888eeae0874ac08e8e80011047b414aa3eb8abbc83c75ad877dfe2481d786b3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
