apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6xef
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6xef
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6xef
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6xef
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6xef
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ccba-tenant/rhtap-demo-app/hacbs-test-project-6xef@sha256:9888eeae0874ac08e8e80011047b414aa3eb8abbc83c75ad877dfe2481d786b3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
